language: java
sudo: false
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml
  || mvn clean verify --settings target/travis/settings.xml"
branches:
  only:
  - develop
